// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISTEMA_DE_CURSOS_MVC.Data;

#nullable disable

namespace SISTEMA_DE_CURSOS_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SISTEMA_DE_CURSOS_MVC.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("TabelaCurso");

                    b.HasDiscriminator<string>("Tipo").HasValue("Curso");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SISTEMA_DE_CURSOS_MVC.Models.Superior", b =>
                {
                    b.HasBaseType("SISTEMA_DE_CURSOS_MVC.Models.Curso");

                    b.HasDiscriminator().HasValue("Superior");
                });

            modelBuilder.Entity("SISTEMA_DE_CURSOS_MVC.Models.Tecnico", b =>
                {
                    b.HasBaseType("SISTEMA_DE_CURSOS_MVC.Models.Curso");

                    b.HasDiscriminator().HasValue("Tecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
